### ISSUE TITLE
Can we install mkl-service in pip?

### ISSUE THREAD

**Issue by BooPatienze** [IntelPython/mkl-service#15]
Due to this few days I cannot use conda to install any packages (use mirrors but no effects), so could we install mkl-service in pip?

**Comment by philipcori** [comment]
pip install mkl

**Comment by yeyingdege** [comment]
Hi there. I got this error "ERROR: Could not find a version that satisfies the requirement mkl-service
ERROR: No matching distribution found for mkl-service" when I install "mkl-service" in my docker image using pip (In my Dockerfile I wrote: RUN pip install mkl-service). My os is Ubuntu 18.04 and my python version is 3.6.x. Could you tell me how to solve this?

**Comment by tomashek** [comment]
Hello @yeyingdege. Right now, mkl-service on PyPI only has builds for python 3.7, that is why you see the error.

In order to use mkl-service with python 3.6, you would need to build it yourself (https://github.com/IntelPython/mkl-service) or install it from a different repository using conda.
