### ISSUE TITLE
Support strict CNR? (MKL_CBWR_STRICT)

### ISSUE THREAD

**Issue by aldanor** [IntelPython/mkl-service#5]
Presumably, this is not supported yet here? Would be sure nice to have it as it's available in 2019.3 release.

**Comment by oleksandr-pavlyk** [comment]
Relevant MKL page: https://software.intel.com/en-us/articles/introduction-to-the-conditional-numerical-reproducibility-cnr

**Comment by aldanor** [comment]
@oleksandr-pavlyk That MKL page is exactly why I posted this issue here :)
